spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    loadbalancer:
      retry:
        enabled: true
    gateway:
      routes:

        - id: fantasytime-admin  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://fantasytime-works
          predicates:
            - Path=/api/FT/**       # 断言，路径相匹配的进行路由
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}



        - id: fantasytime-works  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://fantasytime-works
          predicates:
            - Path=/api/works/**,/api/oss/**       # 断言，路径相匹配的进行路由
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
#
#        - id: fantasytime-third-party  #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://fantasytime-third-party
#          predicates:
#            - Path=/api/oss/**      # 断言，路径相匹配的进行路由
#          filters:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: fantasytime-search  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://fantasytime-search
          predicates:
            - Path=/api/search/**      # 断言，路径相匹配的进行路由
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: go_dialogue  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://go_dialogue
          predicates:
            - Path=/GO/**      # 断言，路径相匹配的进行路由
          filters:
            - RewritePath=/GO/(?<segment>.*),/$\{segment}

        - id: renren-fast  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://renren-fast
          predicates:
            - Path=/api/**         # 断言，路径相匹配的进行路由renren-fast
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


  application:
    name: fantasytime-gateway
server:
  port: 8084

