spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      retry:
        enabled: true
    gateway:
      routes:
        - id: fantasytime-search  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://fantasytime-search
          predicates:
            - Path=/api/search/**       # 断言，路径相匹配的进行路由
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


  application:
    name: fantasytime-gateway
server:
  port: 80


