spring:
  application:
    name: fantasytime-search



    loadbalancer:
      retry:
        enabled: true
  redis:
    port: 6379
    password: xu20010502
    host: 192.168.153.134
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      rate: 1
logging:
  level:
    com.xu: debug
    org.elasticsearch: debug
    tracer: trace
server:
  port: 8083

