#server:
#  port: 8081
#spring:
#  redis:
#    port: 6379
#    host: 47.115.224.241
#    password: xu20010502
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name:  com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.115.224.241:3306/fantasytime?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: xu20010502
#  application:
#    name: fantasytime-works
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.115.224.241:8848
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    port: 5672
#    virtual-host: /
#    # 开启消息成功发送回调
#    publisher-confirm-type: correlated
#    # 开启消息成功被队列接收回调
#    publisher-returns: true
#    # 消息确认模式  NONE 关闭, MANUAL手动, AUTO自动
#    listener:
#      simple:
#        acknowledge-mode: manual
#    # 如果消息成功抵达队列 就以异步的方式优先回调
#    template:
#      mandatory: true
##  zipkin:
##    base-url: http://localhost:9411
##  sleuth:
##    sampler:
##      rate: 1
##  jackson:
##    date-format: yyyy-mm-dd hh:mm:ss
#
#
#
### 配置ThreadPollExecutor 数据
#fantasytime:
#  thread:
#    core-size: 20
#    max-size: 200
#    keep-alive-time: 10
#
### mybatis配置
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    call-setters-on-nulls: true
#  mapper-locations: classpath*:/mapper/**/*.xml
#  type-aliases-package: com.xu.works.entity.*
#
