create table user
(
    Host                     char(255) charset ascii                            default ''                      not null,
    User                     char(32)                                           default ''                      not null,
    Select_priv              enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Insert_priv              enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Update_priv              enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Delete_priv              enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Create_priv              enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Drop_priv                enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Reload_priv              enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Shutdown_priv            enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Process_priv             enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    File_priv                enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Grant_priv               enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    References_priv          enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Index_priv               enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Alter_priv               enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Show_db_priv             enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Super_priv               enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Create_tmp_table_priv    enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Lock_tables_priv         enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Execute_priv             enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Repl_slave_priv          enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Repl_client_priv         enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Create_view_priv         enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Show_view_priv           enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Create_routine_priv      enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Alter_routine_priv       enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Create_user_priv         enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Event_priv               enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Trigger_priv             enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Create_tablespace_priv   enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    ssl_type                 enum ('', 'ANY', 'X509', 'SPECIFIED') charset utf8 default ''                      not null,
    ssl_cipher               blob                                                                               not null,
    x509_issuer              blob                                                                               not null,
    x509_subject             blob                                                                               not null,
    max_questions            int unsigned                                       default '0'                     not null,
    max_updates              int unsigned                                       default '0'                     not null,
    max_connections          int unsigned                                       default '0'                     not null,
    max_user_connections     int unsigned                                       default '0'                     not null,
    plugin                   char(64)                                           default 'caching_sha2_password' not null,
    authentication_string    text                                                                               null,
    password_expired         enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    password_last_changed    timestamp                                                                          null,
    password_lifetime        smallint unsigned                                                                  null,
    account_locked           enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Create_role_priv         enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Drop_role_priv           enum ('N', 'Y') charset utf8                       default 'N'                     not null,
    Password_reuse_history   smallint unsigned                                                                  null,
    Password_reuse_time      smallint unsigned                                                                  null,
    Password_require_current enum ('N', 'Y') charset utf8                                                       null,
    User_attributes          json                                                                               null,
    primary key (Host, User)
)
    comment 'Users and global privileges' collate = utf8_bin;

INSERT INTO mysql.user (Host, User, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv, Create_view_priv, Show_view_priv, Create_routine_priv, Alter_routine_priv, Create_user_priv, Event_priv, Trigger_priv, Create_tablespace_priv, ssl_type, ssl_cipher, x509_issuer, x509_subject, max_questions, max_updates, max_connections, max_user_connections, plugin, authentication_string, password_expired, password_last_changed, password_lifetime, account_locked, Create_role_priv, Drop_role_priv, Password_reuse_history, Password_reuse_time, Password_require_current, User_attributes) VALUES ('%', 'root', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', '', 0x, 0x, 0x, 0, 0, 0, 0, 'mysql_native_password', '*8CF82B44FE31477F126C973486E25F51185AAB01', 'N', '2022-04-25 19:58:36', null, 'N', 'Y', 'Y', null, null, null, null);
INSERT INTO mysql.user (Host, User, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv, Create_view_priv, Show_view_priv, Create_routine_priv, Alter_routine_priv, Create_user_priv, Event_priv, Trigger_priv, Create_tablespace_priv, ssl_type, ssl_cipher, x509_issuer, x509_subject, max_questions, max_updates, max_connections, max_user_connections, plugin, authentication_string, password_expired, password_last_changed, password_lifetime, account_locked, Create_role_priv, Drop_role_priv, Password_reuse_history, Password_reuse_time, Password_require_current, User_attributes) VALUES ('localhost', 'mysql.infoschema', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '', 0x, 0x, 0x, 0, 0, 0, 0, 'caching_sha2_password', '$A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED', 'N', '2022-04-25 19:51:24', null, 'Y', 'N', 'N', null, null, null, null);
INSERT INTO mysql.user (Host, User, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv, Create_view_priv, Show_view_priv, Create_routine_priv, Alter_routine_priv, Create_user_priv, Event_priv, Trigger_priv, Create_tablespace_priv, ssl_type, ssl_cipher, x509_issuer, x509_subject, max_questions, max_updates, max_connections, max_user_connections, plugin, authentication_string, password_expired, password_last_changed, password_lifetime, account_locked, Create_role_priv, Drop_role_priv, Password_reuse_history, Password_reuse_time, Password_require_current, User_attributes) VALUES ('localhost', 'mysql.session', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '', 0x, 0x, 0x, 0, 0, 0, 0, 'caching_sha2_password', '$A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED', 'N', '2022-04-25 19:51:23', null, 'Y', 'N', 'N', null, null, null, null);
INSERT INTO mysql.user (Host, User, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv, Create_view_priv, Show_view_priv, Create_routine_priv, Alter_routine_priv, Create_user_priv, Event_priv, Trigger_priv, Create_tablespace_priv, ssl_type, ssl_cipher, x509_issuer, x509_subject, max_questions, max_updates, max_connections, max_user_connections, plugin, authentication_string, password_expired, password_last_changed, password_lifetime, account_locked, Create_role_priv, Drop_role_priv, Password_reuse_history, Password_reuse_time, Password_require_current, User_attributes) VALUES ('localhost', 'mysql.sys', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', '', 0x, 0x, 0x, 0, 0, 0, 0, 'caching_sha2_password', '$A$005$THISISACOMBINATIONOFINVALIDSALTANDPASSWORDTHATMUSTNEVERBRBEUSED', 'N', '2022-04-25 19:51:24', null, 'Y', 'N', 'N', null, null, null, null);