spring:
  redis:
    port: 6379
    password: xu20010502
    host: 127.0.0.1
  cloud:
    nacos:
      discovery:
        server-addr: 47.115.224.241:8848
  application:
    name: fantasytime-secutity