spring:
  application:
    name: fantasytime-third-party
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.134:8848
server:
  port: 9100

